"use client";

import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { AnimatePresence, motion, useReducedMotion } from "framer-motion";
import { ArrowDown } from "lucide-react";

/**
 * JerseyDrop — Cinematic Legendary Jersey Hero (V8.6).
 *
 * Full-bleed video stage that rotates through 6 cinematic AI clips
 * (one legendary jersey + iconic landmark per clip). Each clip is
 * generated by Higgsfield Veo 3.1 Lite with the BACK of the jersey
 * showing a player surname + number.
 *
 * Transition between clips = a "vortex" swirl: the outgoing video
 * spins out while shrinking + blurring + fading, and the incoming
 * video starts spinning in from the opposite direction at scale 0
 * — both happening simultaneously so the screen visually swirls
 * between jerseys. Total transition ~1.4s.
 *
 * Foreground = ONE element only: the neon-green "קנה עכשיו" CTA
 * bottom-left.
 */

const CLIPS = [
  "/videos/heroes/ronaldo-brazil.mp4",   // Brazil yellow #9
  "/videos/heroes/zidane-france.mp4",    // France navy #10
  "/videos/heroes/messi-argentina.mp4",  // Argentina modern #10
  "/videos/heroes/maradona-argentina.mp4",// Argentina vintage #10
  "/videos/heroes/ronaldo-portugal.mp4", // Portugal red #7
  "/videos/heroes/pele-brazil.mp4",      // Brazil vintage #10
];

const CLIP_DURATION_MS = 7000; // visible per clip, then vortex transition

export default function HeroLegendsRotator() {
  const prefersReduced = useReducedMotion() ?? false;
  const [index, setIndex] = useState(0);
  const containerRef = useRef<HTMLDivElement | null>(null);

  // Cycle through clips
  useEffect(() => {
    if (prefersReduced) return;
    const id = window.setInterval(() => {
      setIndex((i) => (i + 1) % CLIPS.length);
    }, CLIP_DURATION_MS);
    return () => window.clearInterval(id);
  }, [prefersReduced]);

  // Preload next clip image so the swirl-in is smooth (no decode pause)
  useEffect(() => {
    const next = CLIPS[(index + 1) % CLIPS.length];
    const link = document.createElement("link");
    link.rel = "preload";
    link.as = "video";
    link.href = next;
    document.head.appendChild(link);
    return () => {
      document.head.removeChild(link);
    };
  }, [index]);

  const current = CLIPS[index];

  return (
    <section
      ref={containerRef}
      aria-label="Hero"
      className="relative w-full overflow-hidden bg-black"
      style={{ height: "min(100vh, 1080px)" }}
    >
      {/* ============ VORTEX VIDEO LAYER ============ */}
      <AnimatePresence mode="popLayout" initial={false}>
        <motion.video
          key={current}
          src={current}
          autoPlay
          loop
          muted
          playsInline
          preload="auto"
          poster="/videos/heroes/poster.jpg"
          aria-hidden="true"
          initial={
            prefersReduced
              ? { opacity: 1, scale: 1, rotate: 0, filter: "blur(0px)" }
              : { opacity: 0, scale: 0.05, rotate: -720, filter: "blur(24px)" }
          }
          animate={{
            opacity: 1,
            scale: 1,
            rotate: 0,
            filter: "blur(0px)",
            transition: prefersReduced
              ? { duration: 0.2 }
              : {
                  duration: 1.4,
                  ease: [0.16, 1, 0.3, 1], // cubic bezier — fast start, soft land
                },
          }}
          exit={
            prefersReduced
              ? { opacity: 0, transition: { duration: 0.2 } }
              : {
                  opacity: 0,
                  scale: 0.05,
                  rotate: 720,
                  filter: "blur(24px)",
                  transition: {
                    duration: 1.4,
                    ease: [0.7, 0, 0.84, 0], // accelerate into the vortex
                  },
                }
          }
          className="absolute inset-0 h-full w-full object-cover"
          style={{ transformOrigin: "50% 50%", willChange: "transform, opacity, filter" }}
        />
      </AnimatePresence>

      {/* ============ DARK GRADIENT + VIGNETTE OVERLAY ============ */}
      <div
        aria-hidden
        className="pointer-events-none absolute inset-0"
        style={{
          background:
            "linear-gradient(180deg, rgba(0,0,0,0.40) 0%, rgba(0,0,0,0.20) 35%, rgba(0,0,0,0.70) 100%)",
        }}
      />
      <div
        aria-hidden
        className="pointer-events-none absolute inset-0"
        style={{
          background:
            "radial-gradient(ellipse at center, transparent 0%, rgba(0,0,0,0.30) 70%, rgba(0,0,0,0.65) 100%)",
        }}
      />

      {/* ============ THE ONLY VISIBLE FOREGROUND ELEMENT ============ */}
      <motion.div
        initial={{ opacity: 0, y: 16 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6, delay: 0.3, ease: "easeOut" }}
        className="absolute bottom-8 start-6 z-10 sm:bottom-12 sm:start-12"
      >
        <motion.div
          animate={{ scale: [1, 1.04, 1] }}
          transition={{ duration: 2, repeat: Infinity, ease: "easeInOut" }}
        >
          <Link
            href="/products"
            className="group inline-flex items-center gap-2 rounded-full bg-[#00FF88] px-8 py-4 font-display text-lg font-black uppercase tracking-[0.16em] text-black shadow-[0_18px_50px_-10px_rgba(0,255,136,0.55)] transition-all duration-200 ease-out hover:scale-[1.08] hover:brightness-110 sm:px-10 sm:py-5 sm:text-xl"
          >
            קנה עכשיו
            <ArrowDown className="h-5 w-5 transition-transform duration-200 group-hover:translate-y-0.5" />
          </Link>
        </motion.div>
      </motion.div>
    </section>
  );
}
